@host  = http://localhost:5189
@userId = 01a0f8d2-2bd3-717c-99cc-9947da015119

### Obtener todos
GET {{host}}/api/User

### Obtener uno
GET {{host}}/api/User/{{userId}}

### Crear
POST {{host}}/api/User
Content-Type: application/json

{
  "userName": "mario",
  "email": "mario@test.com",
  "password": "1234"
}

### Actualizar
PUT {{host}}/api/User/{{userId}}
Content-Type: application/json

{
  "userName": "mario2",
  "email": "mario2@test.com",
  "password": "5678"
}

### Borrar
DELETE {{host}}/api/User/{{userId}}
